name: Build and Release with PyInstaller and fpm

on:
  # workflow_dispatch:
  push:
    tags:
      - v1.0.**
    branches:
      - 'main'

env:
  VERS: 1.0.1 # ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Add Ruby to PATH
        run: |
          echo "$HOME/.gem/ruby/2.7.0/bin" >> "$GITHUB_PATH"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyInstaller
          gem install dotenv -v 2.8.1
          gem install fpm --user-install
      - name: Package
        run: bash package.sh $VERS #${{ github.ref_name }}
      - name: Check
        run: ls -R
      - name: Store distribution packages
        uses: actions/upload-artifact@v6
        with:
          name: app-distributions
          path: imagecaptureapp-v${{ env.VERS }}.deb


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download all dists
        uses: actions/download-artifact@v7
        with:
          name: app-distributions
          path: dist/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
         # files: dist/**
          files: dist/imagecaptureapp-v${{ env.VERS }}.deb
          body_path: CHANGELOG.txt
          token: ${{ secrets.GITHUB_TOKEN }}
