name: Build Freeze Release with PyInstaller and fpm

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Add Ruby to PATH
        run: |
          echo "$PATH"
          echo "$HOME"
          echo "$HOME/.gem/ruby/2.7.0/bin" >> "$GITHUB_PATH"
          echo "$GITHUB_PATH"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyInstaller
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          gem install fpm --user-install
      - name: Build with PyInstaller
        run: pyinstaller pyinstaller.spec --noconfirm
      - name: Package
        run: bash package.sh
      - name: fpm
        run: fpm
